- set_attrs :   #name      : vanilla
    shift_sampling_window:  null
    shift_limits: 0
    params: ste
  fit_args  :
    X       : train
    lengths : lengths
    X_val   : validation
    lengths_val : lengths_val
- set_attrs :
    shift_sampling_window:  null
    shift_limits: 0
    params: e
  fit_args  :
    X       : train2[:${num_pretraining_samples}*${length}]
    lengths : lengths[:${num_pretraining_samples}]
    # X_val   : validation
    # lengths_val : lengths_val