params:
  mu    : 10

name : poisson

func_type : logpmf
estimated_param_name : [mu]

dist:
  _target_  : scipy.stats.poisson
  _partial_ : true

estimator:
  _target_  : numpy.mean
  _partial_ : true
  axis      : 0
  keepdims  : true

estimator_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${estimator}
  in_keys   : [data_samples]
  out_keys  : [mu]


#norm:
#  _target_    : utils.setattrs_kwargs
#  target      :
#  _target_  : scipy.stats.distributions.norm_gen
#  name      : norm
#  sigma : 1
#  loc   : 0

