#args_for_model_partial:
#  X_train: ${eval:'train'}
#  lengths: ${lengths}
#
#
#
#args_for_fit:
#  X: ${eval:'train'}
#  lengths: ${lengths}
#  X_val: ${eval:'val'}
#  lengths_val: ${lengths}
#

lengths:
  - ${eval:${length} * ${train_trials}}

lengths_val:
  - ${eval:${length} * ${val_trials}}

model:
  model:
    shift_sampling_window: 0
    shift_limits: 10


#X_train: ???
#train_trials: ???
#length: ???
#val_trials: ???