defaults:
#######  Teacher ##########
#  - model@teacher: partial_chain_multivariate_bernoulli
#  - model@teacher: partial_chain_multivariate_poisson
#  - model@teacher: chain_multivariate_poisson
  - model@teacher: chain_multivariate_bernoulli

##### datamodule ##########
  - default_breakup
#  - nlb_mc_maze_breakup
  - datamodule: nlb_mc_maze

#### decoding ####
  - decoding: logistic

#######  Student ##########
  - model@student: chain_multivariate_bernoulli
#  - model@student: chain_multivariate_poisson #basic_multivariate_poisson

####### Initial manipulation
#  - manipulation@initial_manipulation: enlarger_with_onehot
  - manipulation@initial_manipulation: identity

#######  Manipulations ##########
#  - manipulation: inconsequential_enlarger
#  - manipulation: enlarger_with_onehot
  - manipulation: identity

######## dynamax algorithm ######
#  - dynamax: em
  - dynamax: adam

#######  bits_per_spike_func ##########
  - bits_per_spike_func: bernoulli
#  - bits_per_spike_func: poisson
  - _self_

###########################
  - path_to_save_files

####### multirun ##########
#  - hydra: multirun_cohmm
#  - hydra: multirun_cohmm_scan_training_iterations
#  - override hydra/launcher: joblib

data_mode: student-teacher
#data_mode: nlb

use_teacher_as_student: false
#use_teacher_as_student: true

initialise_student_as_teacher: false
#initialise_student_as_teacher: true

#emission_mode : poisson
emission_mode : bernoulli

# for analysis only put save_trained: false, run_train: true with zero epochs to get the correct name
run_train     : true
save_trained  : true
load_student_for_analysis: true
run_analysis  : true
save_results  : true

# training_framework  : hmmlearn
training_framework  : dynamax

#initialise_dynamax: true
initialise_dynamax: false

analysis:
  compute_similarity_metrics        : false
  compute_latent_decoding_linear    : true
  compute_latent_decoding           : false
  compute_mutual_info               : false
  compute_latent_decoding_shuffled  : false
  plot_student_matrices             : false
  compute_k_shot                    : true
  compute_co_smoothing              : true
  compute_latent_decoding_stepwise  : false
  compute_fisher_info_matrix        : false
  compute_k_shot_jax                : false  # requires compute_fisher_info_matrix: true

jax_MLE_func:
  _target_  : hmm_fisher_info.batch_compute_${emission_mode}_MLE
  _partial_ : true

numpy_seed:
  _target_  : numpy.random.seed
  seed      : 0



neurons_split_indices:
  - ${num_neurons_heldin}
  - ${eval:${num_neurons_heldin}+${num_neurons_heldout}}


student_subpath: models_traintrials${train_trials}/ncomp${student.n_components}_${student_name}_id${student_index}
teacher_save_path: ${path_to_save_files}/all_models_validated_v2/teacher_state${teacher.n_components}_${emission_mode}_partial_eps${teacher.transmat_epsilon}_length${length}
student_save_path: ${teacher_save_path}/${student_subpath}

##################

num_neurons_total: ${eval:${num_neurons_heldin}+${num_neurons_heldout}+${num_neurons_reallyheldout}}
total_trials: ${eval:${train_trials}+${val_trials}+${test_trials}}

teacher:
  n_features: ${num_neurons_total}
  n_components: 4
  transmat_epsilon: 1e-2

student:
  random_state:
    _target_: numpy.random.RandomState
    seed    : ${student_index}
  n_components: 8
#  n_features  : ${eval:${num_neurons_heldin}+${num_neurons_heldout}}

student_index: 4

####### training config
training_config:
  - n_iter: 100
    params: stl
    init_params: stl

#  - shift_sampling_window: ${eval:${length} - ${.shift_limits}}
#    shift_limits: 1
#  - shift_sampling_window: null
#    shift_limits: 0

#student_name: shifts_then_noshifts
student_name: vanilla



generate_all_data:
  _target_  : prepare_model.sample_hmm
  _partial_ : true
#  hmm_model : ${teacher}
  length    : ${length}
  trials    : ${eval:'(${train_trials}+${val_trials}+${test_trials})'}
  flatten   : false

generate_all_data_with_states:
  _target_  : prepare_model.sample_hmm
  _partial_ : true
#  hmm_model : ${teacher}
  length    : ${length}
  trials    : ${eval:'(${train_trials}+${val_trials}+${test_trials})'}
  flatten   : false
  return_states: true


numpy_to_xarray_with_breakdownlabels:
  _target_  : utils.MultiSelectDataArray  #xarray.DataArray
#  data      :
  _partial_ : true
  dims      : [trials,time,neurons]
  coords    :
    trials_split : ${as_tuple:trials,${eval:${listmul:train,${train_trials}}+
                                            ${listmul:val,${val_trials}}+
                                            ${listmul:test,${test_trials}}}}
    neurons_split : ${as_tuple:neurons,${eval:${listmul:heldin,${num_neurons_heldin}} +
                       ${listmul:heldout,${num_neurons_heldout}} +
                       ${listmul:reallyheldout,${num_neurons_reallyheldout}}}}

numpy_to_xarray_with_breakdownlabels_split2:
  _target_  : utils.MultiSelectDataArray  #xarray.DataArray
#  data      :
  _partial_ : true
  dims      : [trials,time,neurons]
  coords    :
    trials_split : ${as_tuple:trials,${eval:${listmul:train,${train_trials}}+
                                            ${listmul:val,${val_trials}}+
                                            ${listmul:test,${test_trials}}}}
    neurons_split : ${as_tuple:neurons,${eval:${listmul:heldin,${num_neurons_heldin}} +
                       ${listmul:heldout,${num_neurons_heldout}}}}
#numpy_to_xarray_with_breakdownlabels_instantiated:
#  _target_: config_utils.instantiate
#  ${numpy_to_xarray_with_breakdownlabels}
#  '_convert_' : partial

numpy_to_xarray_with_breakdownlabels_states:
  _target_  : utils.MultiSelectDataArray  #xarray.DataArray
#  data      :
  _partial_ : true
  dims      : [trials,time,features]
  coords    :
    trials_split : ${as_tuple:trials,${eval:${listmul:train,${train_trials}}+
                                            ${listmul:val,${val_trials}}+
                                            ${listmul:test,${test_trials}}}}




###### Dict config generate ########

hmm_sample_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${generate_all_data}
  in_keys   : [hmm_model]
  out_keys  : [data_numpy]

hmm_sample_with_states_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${generate_all_data_with_states}
  in_keys   : [hmm_model]
  out_keys  : [data_numpy,states_data_numpy]

dataarray_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${numpy_to_xarray_with_breakdownlabels}
  in_keys : [[data_numpy,data]]
  out_keys: [data_xarray]

dataarray_split2_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${numpy_to_xarray_with_breakdownlabels_split2}
  in_keys : [[data_numpy,data]]
  out_keys: [data_xarray]

dataarray_states_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${numpy_to_xarray_with_breakdownlabels_states}
  in_keys : [[states_data_numpy,data]]
  out_keys: [states_data_xarray]

generate_all_data_dictsequential:
  _target_: config_utils.dict_module.DictSequential
  _args_  :
    - ${hmm_sample_dictmodule}
    - ${dataarray_dictmodule}

generate_all_data_with_states_dictsequential:
  _target_: config_utils.dict_module.DictSequential
  _args_  :
    - ${hmm_sample_with_states_dictmodule}
    - ${dataarray_split2_dictmodule}
    - ${dataarray_states_dictmodule}


generate_all_data_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${generate_all_data_dictsequential}
  in_keys : [hmm_model]
  out_keys: [[data_xarray,null]]

generate_all_data_with_states_dictmodule:
  _target_: config_utils.dict_module.DictModule
  module  : ${generate_all_data_with_states_dictsequential}
  in_keys : [hmm_model]
  out_keys: [data_xarray,states_data_xarray]

################


#generate_train_val_test_split:
#  _target_ : numpy.split
#  _partial_: true
##  ary      : ${all_data}
#  indices_or_sections:
#    - ${eval:'${train_trials}'}
#    - ${eval:'${train_trials}+${val_trials}'}
#  axis: 0



######## Data break-up #######
breakups_dictmodule:
  fit:
    _target_: config_utils.dict_module.DictModule
    module:
      _target_: config_utils.dict_module.DictSequential
      _args_:
        - _target_: config_utils.dict_module.DictModule
          module:
            _target_: utils.select
            _partial_: true
            trials_split: train
            neurons_split: [ heldin,heldout ]
          in_keys : [[data,obj]]
          out_keys: [selected_train]
        - _target_: config_utils.dict_module.DictModule
          module:
            _target_: utils.select
            _partial_: true
            trials_split: val
            neurons_split: [ heldin,heldout ]
          in_keys   : [[data, obj]]
          out_keys  : [selected_val] #[X_val,lengths_val]
        - _target_  : config_utils.dict_module.DictModule
          module    :
            _target_  : utils.flatten_with_lengths
            _partial_ : true
          in_keys   : [[selected_train,array]]
          out_keys  : [X,lengths]
        - _target_  : config_utils.dict_module.DictModule
          module    :
            _target_  : utils.flatten_with_lengths
            _partial_ : true
          in_keys   : [[selected_val,array]]
          out_keys  : [X_val,lengths_val]

    in_keys : [data]
    out_keys: [X,lengths,X_val,lengths_val]
#    out_keys: [selected_train,selected_val]



breakups:
  fit:
    train:
      trials_split: train
      neurons_split: [heldin,heldout]
    val:
      trials_split: val
      neurons_split: [heldin,heldout]

  k_shot_fit:
    input:
      trials_split: train
      neurons_split: heldin
    target:
      trials_split: train
      neurons_split: reallyheldout

  k_shot_test:
    input:
      trials_split: test
      neurons_split: heldin
    target:
      trials_split: test
      neurons_split: reallyheldout

  cosmoothing:
    input:
      trials_split: test
      neurons_split: heldin
    target:
      trials_split: test
      neurons_split: heldout

  decoding:
    fit:
      input:
        trials_split  : train
        neurons_split : heldin
      states:
        trials_split  : train
    test:
      input:
        trials_split  : test
        neurons_split : heldin
      states:
        trials_split  : test
######### Analysis ##########




similarity_measures:
  procrustes:
    _target_  : similarity.make
    key       : measure.procrustes
    interface :
      fit_score: '__call__'
  procrustes-angular:
    _target_  : similarity.make
    key       : measure.procrustes-angular
    interface :
      fit_score: '__call__'
#  linear_regression:
#    _target_  : similarity.make
#    key       : measure.linear_regression
#    interface :
#      fit_score: '__call__'
